//@version=3
study(title="Fibonacci EMA's", overlay=true)

sLen=input(title="Short EMA Length", defval=13)
mLen=input(55, title="Mid EMA Length")
lLen=input(89, title="Long EMA Length")

sEMA=ema(close,shortEMA)
mEMA=ema(close,midEMA)
lEMA=ema(close,longEMA)

currentOrder = 0
prevOrder = nz(currentOrder[1],0)
currentOrder := (sEMA > mEMA and mEMA > lEMA) ? 1 : ((lEMA > mEMA and mEMA > sEMA) ? -1 : 0)
orderChange = currentOrder != prevOrder

//crossed=cross(sEMA,lEMA)

p1=plot(sEMA, title="Short EMA", color=blue, linewidth=3, transp=0)
plot(mEMA, title="Mid EMA", color=green, linewidth=3, transp=0)
p2=plot(lEMA, title="Long EMA", color=yellow, linewidth=3, transp=0, editable=false)

//plotarrow(crossed?sEMA-lEMA:na, title="EMA Cross", colorup=lime, colordown=red, transp=0, maxheight=20, minheight=20)

bgcolor(orderChange?bgc:na,title="EMA Order Crossed")
fill(p1,p2,bgc)

sEMAForecast1 = linreg(close,3,1)
sFP1=((ema(close,sLen-1)*(sLen-1))+sEMAForecast1)/sLen
plot(sFP1,title="Short EMA F1",style=circles,linewidth=2,color=blue,offset=1,show_last=1)

sEMAForecast2 = linreg(close,3,2)
sFP2=((ema(close,sLen-2)*(sLen-2))+sEMAForecast1+sEMAForecast2)/sLen
plot(sFP2,title="Short EMA F2",style=circles,linewidth=2,color=blue,offset=2,show_last=1)

sEMAForecast3 = linreg(close,3,3)
sFP3=((ema(close,sLen-3)*(sLen-3))+sEMAForecast1+sEMAForecast2+sEMAForecast3)/sLen
plot(sFP3,title="Short EMA F3",style=circles,linewidth=2,color=blue,offset=3,show_last=1)
