// This source code is subject to the terms of the Osozilla Public License 2.0 at https://mozilla.org/OsPL/2.0/
// © BlueJayBird

// @version=4
study(title="[bjb] SVO - Simple Volume Oscillator, by @BlueJayBird", shorttitle="SVO", format = format.price, precision = 2, scale = scale.right)

// ------------------------------------------------------------ Constants
transparency = 0
drawOnRealTime = true // "Draw On Candles Yet To Close"

// ------------------------------------------------------------ Inputs
// SVO
enable_svo = input(title = "Enable Simple Volume Oscillator (SVO)", type = input.bool, defval = true) 
svo_length = input(defval = 14, minval = 1, title="SVO Length", type = input.integer)
svo_smoothing = input(defval = 21, minval = 1, title="SVO Smoothing", type = input.integer)
svo_resolution = input(defval = "", title = "SVO Resolution", type = input.resolution)
// Background
enable_bg = input(true, title="Enable Background")

// SVO to oscillator values (RSIed)
svo_rsied = rsi(vwma(volume, svo_smoothing), svo_length)
svo_security = security(syminfo.tickerid, svo_resolution , svo_rsied)

// ------------------------------------------------------------ Plotting
// Color Palette
color_a = color.new(color.lime, 40)
color_b = color.new(color.green, 40)
color_c = color.new(color.yellow, 40)
color_d = color.new(color.orange, 40)
color_e = color.new(color.red, 40)
color_extremes =  color.new(color.silver, 40)
// SVO
plot(enable_svo ? svo_security : na, color = color.yellow, title = "SVO", editable = true)
// Background lines
line_100 = hline(enable_bg ? 100 : na, title = "Level 100", color = color_extremes, linestyle = hline.style_dashed, editable = true)
line_80 = hline(enable_bg ? 80 : na, title = "Level 80", color = color_d, linestyle = hline.style_dashed, editable = true)
line_60 = hline(enable_bg ? 60 : na, title = "Level 60", color = color_c, linestyle = hline.style_dashed, editable = true)
line_40 = hline(enable_bg ? 40 : na, title = "Level 40", color = color_b, linestyle = hline.style_dashed, editable = true)
line_20 = hline(enable_bg ? 20 : na, title = "Level 20", color = color_a, linestyle = hline.style_dashed, editable = true)
line_0 = hline(enable_bg ? 0 : na, title = "Level 0", color = color_extremes, linestyle = hline.style_dashed, editable = true)
// Background colors
bgc_0_20 = color.new(color.lime, 90)
bgc_20_40 = color.new(color.green, 90)
bgc_40_60 = color.new(color.yellow, 90)
bgc_60_80 = color.new(color.orange, 90)
bgc_80_100 = color.new(color.red, 90)
// Backgrpund fills
fill(line_0, line_20, color = bgc_0_20, editable = true)
fill(line_20, line_40, color = bgc_20_40, editable = true)
fill(line_40, line_60, color = bgc_40_60, editable = true)
fill(line_60, line_80, color = bgc_60_80, editable = true)
fill(line_80, line_100, color = bgc_80_100, editable = true)

// END