// This source code is subject to the terms of the Osozilla Public License 2.0 at https://mozilla.org/OsPL/2.0/
// © BlueJayBird
// @author @BlueJayBird
// @version=4

study(title="Moving Averages, by @BlueJayBird", shorttitle="MAs", format=format.price, overlay=true)

// If this has helped you to improve your trading and therefore your income, any donation is appreciated:
// BTC: 3Dj9jfGuJ861oEH7kA1zpgMssPw2PYF7Gq
// ETH and USDT: 0xc8645305ab8c08f08bcbc89c020b63362527f771

// ------------------------------------------------- MAs
movingAverage = input(title = "Type MAs", defval = "EMA", options = ["EMA", "MA", "RMA", "SMMA", "VWMA", "WMA"])
price = input(type=input.source, defval=low,  title = "Source MAs")
enable_a = input(true,  title = "Enable MAs L1")
enable_bB = input(true,  title = "Enable MAs L2")
enable_cC = input(true,  title = "Enable MAs L3")
enable_dD = input(true,  title = "Enable MAs L4")
enable_eE = input(true,  title = "Enable MAs L5")
enable_common = input(false,  title = "Enable MAs[20][50][200]")
// Fill Type
enable_a_fill_b = false, enable_a_fill_B = false, enable_a_fill_50 = false
fill_type = input(title = "Fill Type", defval = "None", options = ["None", "[a] to [b]", "[a] to [B]", "[20] to [50]"])
if fill_type == "[a] to [b]"
	enable_a_fill_b := true
else if fill_type == "[a] to [B]"
	enable_a_fill_B := true
else if fill_type == "[20] to [50]"
	enable_a_fill_50 := true
else
	enable_a_fill_b := false
	enable_a_fill_B := false
	enable_a_fill_50 := false

// cMA
enable_custom = input(false,  title = "Enable Custom MA [MAc]")
movingAverageCustom = input(title = "Type MAc (Custom)", defval = "VWMA", options = ["EMA", "MA", "RMA", "SMMA", "VWMA", "WMA"])
length_custom = input(defval=20,  title = "Length MAc (Custom)")

// Style
thickness = 2
transp_ma = 40
transp_fill = 90
transp_fill_20 = 80
securityGap = barmerge.gaps_off
securityLookahead = barmerge.lookahead_on

// Colors
color_1m = color.aqua
color_5m = color.fuchsia
color_15m = color.orange
color_30m = color.red
color_1h = color.yellow
color_4h = color.lime
color_1D = color.gray
color_1W = color.silver
color_1M = color.white
color_custom = color.gray
color_20 = timeframe.period == "1" ? color_1m : timeframe.period == "5" ? color_5m : timeframe.period == "15" ? color_15m : timeframe.period == "30" ? color_30m : timeframe.period == "60" ? color_1h : timeframe.period == "240" ? color_4h : timeframe.period == "D" ? color_1D : timeframe.period == "W" ? color_1W : timeframe.period == "M" ? color_1M : color.white
color_50 = color.fuchsia
color_200 = #FF43A4


//  MOVING AVERAGES
float ma20 = na,    float ma50 = na,    float ma60 = na
float ma80 = na,	float ma100 = na,	float ma120 = na
float ma140 = na,	float ma200 = na,	float ma300 = na
float ma320 = na,	float ma400 = na,	float ma480 = na
float ma600 = na,	float ma840 = na,	float ma1200 = na 
float ma1600 = na,	float ma1920 = na,	float ma3360 = na 
float ma3600 = na,	float ma3840 = na,	float ma4800 = na 
float maCustom_1 = na
float maCustom_2 = na

smma(sourceSMMA, lenSMMA) =>
    float valueSMMA = na
    localSMA = sma(sourceSMMA, lenSMMA)
    valueSMMA := na(valueSMMA[1]) ? localSMA : (valueSMMA[1] * (lenSMMA - 1) + sourceSMMA) / lenSMMA

// Imported Moving Averages
ma20security = ema(price, 20)
ma20_5 = security(syminfo.tickerid, "5", ma20security, securityGap, securityLookahead)
ma20_30 = security(syminfo.tickerid, "30", ma20security, securityGap, securityLookahead)
ma20_60 = security(syminfo.tickerid, "60", ma20security, securityGap, securityLookahead)
ma20_240 = security(syminfo.tickerid, "240", ma20security, securityGap, securityLookahead)
ma20_D = security(syminfo.tickerid, "D", ma20security, securityGap, securityLookahead)
ma20_W = security(syminfo.tickerid, "W", ma20security, securityGap, securityLookahead)
ma20_M = security(syminfo.tickerid, "M", ma20security, securityGap, securityLookahead)

// MA Values
if movingAverage == "EMA"
	ma20 := ema(price, 20),		ma50 := ema(price, 50),		ma60 := ema(price, 60)
	ma80 := ema(price, 80),		ma100 := ema(price, 100),	ma120 := ema(price, 120)
	ma140 := ema(price, 140),	ma200 := ema(price, 200),	ma300 := ema(price, 300)
	ma320 := ema(price, 320),	ma400 := ema(price, 400),	ma480 := ema(price, 480)
	ma600 := ema(price, 600),	ma840 := ema(price, 840),	ma1200 := ema(price, 1200)
	ma1600 := ema(price, 1600), ma1920 := ema(price, 1920),	ma3360 := ema(price, 3360)
	ma3600 := ema(price, 3600),	ma3840 := ema(price, 3840),	ma4800 := ema(price, 4800)
if movingAverage == "MA"
	ma20 := sma(price, 20),		ma50 := sma(price, 50),		ma60 := sma(price, 60)
	ma80 := sma(price, 80),		ma100 := sma(price, 100),	ma120 := sma(price, 120)
	ma140 := sma(price, 140),	ma200 := sma(price, 200),	ma300 := sma(price, 300)
	ma320 := sma(price, 320),	ma400 := sma(price, 400),	ma480 := sma(price, 480)
	ma600 := sma(price, 600),	ma840 := sma(price, 840),	ma1200 := sma(price, 1200)
	ma1600 := sma(price, 1600), ma1920 := sma(price, 1920),	ma3360 := sma(price, 3360)
	ma3600 := sma(price, 3600),	ma3840 := sma(price, 3840),	ma4800 := sma(price, 4800)
if movingAverage == "RMA"
	ma20 := rma(price, 20),		ma50 := rma(price, 50),		ma60 := rma(price, 60)
	ma80 := rma(price, 80),		ma100 := rma(price, 100),	ma120 := rma(price, 120)
	ma140 := rma(price, 140),	ma200 := rma(price, 200),	ma300 := rma(price, 300)
	ma320 := rma(price, 320),	ma400 := rma(price, 400),	ma480 := rma(price, 480)
	ma600 := rma(price, 600),	ma840 := rma(price, 840),	ma1200 := rma(price, 1200)
	ma1600 := rma(price, 1600), ma1920 := rma(price, 1920),	ma3360 := rma(price, 3360)
	ma3600 := rma(price, 3600),	ma3840 := rma(price, 3840),	ma4800 := rma(price, 4800)
if movingAverage == "SMMA"
    ma20 := smma(price, 20),		ma50 := smma(price, 50),		ma60 := smma(price, 60)
	ma80 := smma(price, 80),		ma100 := smma(price, 100),		ma120 := smma(price, 120)
	ma140 := smma(price, 140),		ma200 := smma(price, 200),		ma300 := smma(price, 300)
	ma320 := smma(price, 320),		ma400 := smma(price, 400),		ma480 := smma(price, 480)
	ma600 := smma(price, 600),		ma840 := smma(price, 840),		ma1200 := smma(price, 1200)
	ma1600 := smma(price, 1600), 	ma1920 := smma(price, 1920),	ma3360 := smma(price, 3360)
	ma3600 := smma(price, 3600),	ma3840 := smma(price, 3840),	ma4800 := smma(price, 4800)
if movingAverage == "VWMA"
	ma20 := vwma(price, 20),		ma50 := vwma(price, 50),		ma60 := vwma(price, 60)
	ma80 := vwma(price, 80),		ma100 := vwma(price, 100),		ma120 := vwma(price, 120)
	ma140 := vwma(price, 140),		ma200 := vwma(price, 200),		ma300 := vwma(price, 300)
	ma320 := vwma(price, 320),		ma400 := vwma(price, 400),		ma480 := vwma(price, 480)
	ma600 := vwma(price, 600),		ma840 := vwma(price, 840),		ma1200 := vwma(price, 1200)
	ma1600 := vwma(price, 1600),	ma1920 := vwma(price, 1920),	ma3360 := vwma(price, 3360)
	ma3600 := vwma(price, 3600),	ma3840 := vwma(price, 3840),	ma4800 := vwma(price, 4800)
if movingAverage == "WMA"
	ma20 := wma(price, 20),		ma50 := wma(price, 50),		ma60 := wma(price, 60)
	ma80 := wma(price, 80),		ma100 := wma(price, 100),	ma120 := wma(price, 120)
	ma140 := wma(price, 140),	ma200 := wma(price, 200),	ma300 := wma(price, 300)
	ma320 := wma(price, 320),	ma400 := wma(price, 400),	ma480 := wma(price, 480)
	ma600 := wma(price, 600),	ma840 := wma(price, 840),	ma1200 := wma(price, 1200)
	ma1600 := wma(price, 1600), ma1920 := wma(price, 1920),	ma3360 := wma(price, 3360)
	ma3600 := wma(price, 3600),	ma3840 := wma(price, 3840),	ma4800 := wma(price, 4800)

// MAc Values
if movingAverageCustom == "EMA"
	maCustom_1 := ema(high, length_custom)
	maCustom_2 := ema(low, length_custom)
if movingAverageCustom == "MA"
	maCustom_1 := sma(high, length_custom)
	maCustom_2 := sma(low, length_custom)
if movingAverageCustom == "RMA"
	maCustom_2 := rma(high, length_custom)
	maCustom_1 := rma(low, length_custom)
if movingAverageCustom == "SMMA"
	maCustom_1 := smma(high, length_custom)
	maCustom_2 := smma(low, length_custom)
if movingAverageCustom == "VWMA"
	maCustom_1 := vwma(high, length_custom)
	maCustom_2 := vwma(low, length_custom)
if movingAverageCustom == "WMA"
	maCustom_1 := wma(high, length_custom)
	maCustom_2 := wma(low, length_custom)

// Favorite timeframes: 1m, 15m, 1h, 4h, 1D, 1W

// -------------------------------------------------- MA Custom
maCustom_1_plot = plot(enable_custom ? maCustom_1 : na,  title = "[CHigh]", color = color_custom, linewidth=1, transp = transp_ma, editable=true)
maCustom_2_plot = plot(enable_custom ? maCustom_2 : na,  title = "[CLow]", color = color_custom, linewidth=2, transp = transp_ma, editable=true)
bgc_maCustom = color.new(color.gray, 80)
fill(maCustom_1_plot, maCustom_2_plot, bgc_maCustom, editable=true, title = "CFill")

// -------------------------------------------------- 1m
ma20_plot_a_1 = plot(enable_a and timeframe.period == "1" ? ma20 : na,  title = "1m" , color = color_1m, linewidth = thickness, transp = transp_ma, editable = false)
ma100_plot_b_1 = plot(enable_bB and timeframe.period == "1" ? ma100 : na,  title = "5m", color = color_5m, linewidth = thickness, transp = transp_ma, editable = false)
ma20_5_plot_B_1 = plot(enable_bB and timeframe.period == "1" ? ma20_5 : na,  title = "5m", color = color_5m, linewidth = thickness, transp = transp_ma, editable = false)
bgc_abB_1 = iff(ma20 > ma100, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_bB_1 = color.new(color_5m, transp_fill)
fill(ma20_plot_a_1, ma100_plot_b_1, enable_a_fill_b ? bgc_abB_1 : na, editable = false)
fill(ma20_plot_a_1, ma20_5_plot_B_1, enable_a_fill_B ? bgc_abB_1 : na, editable = false)
fill(ma100_plot_b_1, ma20_5_plot_B_1, bgc_bB_1, editable = false)
// 30m
ma600_plot_c_1 = plot(enable_cC and timeframe.period == "1" ? ma600 : na,  title = "30m", color = color_30m, linewidth = thickness, transp = transp_ma, editable = false)
ma20_30_C_1 = plot(enable_cC and timeframe.period == "1" ? ma20_30 : na,  title = "30m", color = color_30m, linewidth = thickness, transp = transp_ma, editable = false)
bgc_cC_1 = color.new(color_30m, transp_fill)
fill(ma600_plot_c_1, ma20_30_C_1, bgc_cC_1, editable = false)
// 1h
ma1200_plot_d_1 = plot(enable_dD and timeframe.period == "1" ? ma1200 : na,  title = "1h", color = color_1h, linewidth = thickness, transp = transp_ma, editable = false)
ma20_60_D_1 = plot(enable_dD and timeframe.period == "1" ? ma20_60 : na,  title = "1h", color = color_1h, linewidth = thickness, transp = transp_ma, editable = false)
bgc_dD_1 = color.new( color_1h, transp_fill)
fill(ma1200_plot_d_1, ma20_60_D_1, bgc_dD_1, editable = false)
// 4h
ma4800_plot_e = plot(enable_eE and timeframe.period == "1" ? ma4800 : na,  title = "4h", color =  color_4h, linewidth = thickness, transp = transp_ma, editable = false)
ma20_240_E = plot(enable_eE and timeframe.period == "1" ? ma20_240 : na,  title = "4h", color = color_4h, linewidth = thickness, transp = transp_ma, editable = false)
bgc_eE = color.new(color.lime, transp_fill)
fill(ma4800_plot_e, ma20_240_E, bgc_eE, editable = false)

// --------------------------------------------------  3m


// --------------------------------------------------  5m
ma20_plot_a_5 = plot(enable_a and timeframe.period == "5" ? ma20 : na,  title = "5m" , color = color_5m, linewidth = thickness, transp = transp_ma, editable = false)


// -------------------------------------------------- 15m
// 15m, 1h
ma20_plot_a_15 = plot(enable_a and timeframe.period == "15" ? ma20 : na,  title = "15m", color = color_15m, linewidth = thickness, transp = transp_ma, editable = false)
ma80_plot_b_15 = plot(enable_bB and timeframe.period == "15" ? ma80 : na,  title = "1h", color = color_1h, linewidth = thickness, transp = transp_ma, editable = false)
ma20_60_plot_B_15 = plot(enable_bB and timeframe.period == "15" ? ma20_60 : na,  title = "1h", color = color_1h, linewidth = thickness, transp = transp_ma, editable = false)
bgc_ab_15 = iff(ma20 > ma80, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_aB_15 = iff(ma20 > ma20_60, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_bB_15 = color.new(color.yellow, transp_fill)
fill(ma20_plot_a_15, ma80_plot_b_15, enable_a_fill_b ? bgc_ab_15 : na, editable = false)
fill(ma20_plot_a_15, ma20_60_plot_B_15, enable_a_fill_B ? bgc_aB_15 : na, editable = false)
fill(ma80_plot_b_15, ma20_60_plot_B_15, color_1h, editable = false)
// 4h
ma320_plot_c_15 = plot(enable_cC and timeframe.period == "15" ? ma320 : na,  title = "4h", color = color_4h, linewidth = thickness, transp = transp_ma, editable = false)
ma20_240_plot_C_15 = plot(enable_cC and timeframe.period == "15" ? ma20_240 : na,  title = "4h", color = color_4h, linewidth = thickness, transp = transp_ma, editable = false)
bgc_cC_15 = color.new(color_4h, transp_fill)
fill(ma320_plot_c_15, ma20_240_plot_C_15, bgc_cC_15, editable = false)
// 1D
ma1920_plot_e_15 = plot(enable_dD and timeframe.period == "15" ? ma1920 : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
ma20_D_plot_E_15 = plot(enable_dD and timeframe.period == "15" ? ma20_D : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
bgc_dD_15 = color.new(color_1D, transp_fill)
fill(ma1920_plot_e_15, ma20_D_plot_E_15, bgc_dD_15, editable = false)
// 1W
// ma13440_plot_e = plot(enable_eE and timeframe.period == "15" ? ma13440 : na,  title = "[e]", color = color_eE, linewidth = thickness, transp = transp_ma, editable = false)
plot(enable_eE and timeframe.period == "15" ? ma20_W : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)
// bgc_eE_15 = color.new(color_eE, transp_fill)
// fill(ma13440_plot_e, ma20_W_plot_E, bgc_eE_15, editable = false)

// -------------------------------------------------- 30m
ma20_plot_a_30 = plot(enable_a and timeframe.period == "30" ? ma20 : na,  title = "30m" , color = color_30m, linewidth = thickness, transp = transp_ma, editable = false)

// -------------------------------------------------- 1h
// 1h, 4h
ma20_plot_a_60 = plot(enable_a and timeframe.period == "60" ? ma20 : na,  title = "1h", color = color_1h, linewidth = thickness, transp = transp_ma, editable = false)
ma80_plot_b_60 = plot(enable_bB and timeframe.period == "60" ? ma80 : na,  title = "4h", color = color_4h, linewidth = thickness, transp = transp_ma, editable = false)
ma20_240_plot_B_60 = plot(enable_bB and timeframe.period == "60" ? ma20_240 : na,  title = "4h", color = color_4h, linewidth = thickness, transp = transp_ma, editable = false)
bgc_ab_60 = iff(ma20 > ma80, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_aB_60 = iff(ma20 > ma20_240, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_bB_60 = color.new(color_4h, transp_fill)
fill(ma20_plot_a_60, ma80_plot_b_60, enable_a_fill_b ? bgc_ab_60 : na, editable = false)
fill(ma20_plot_a_60, ma20_240_plot_B_60, enable_a_fill_B ? bgc_aB_60 : na, editable = false)
fill(ma80_plot_b_60, ma20_240_plot_B_60, bgc_bB_60, editable = false)
// 1D
ma480_plot_c_60 = plot(enable_cC and timeframe.period == "60" ? ma480 : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
ma20_D_plot_C_60 = plot(enable_cC and timeframe.period == "60" ? ma20_D : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
bgc_cC_60 = color.new(color_1D, transp_fill)
fill(ma480_plot_c_60, ma20_D_plot_C_60, bgc_cC_60, editable = false)
// 1W
ma3360_plot_d_60 = plot(enable_dD and timeframe.period == "60" ? ma3360 : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)
ma20_D_plot_D_60 = plot(enable_dD and timeframe.period == "60" ? ma20_W : na,  title = "1W", color =  color_1W, linewidth = thickness, transp = transp_ma, editable = false)
bgc_dD_60 = color.new(color_1W, transp_fill)
fill(ma3360_plot_d_60, ma20_D_plot_D_60, bgc_dD_60, editable = false)

// -------------------------------------------------- 4h
// 4h, 1D
ma20_plot_a_240 = plot(enable_a and timeframe.period == "240" ? ma20 : na,  title = "4h", color = color_4h, linewidth = thickness, transp = transp_ma, editable = false)
ma120_plot_b_240 = plot(enable_bB and timeframe.period == "240" ? ma120 : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
ma20_D_plot_B_240 = plot(enable_bB and timeframe.period == "240" ? ma20_D : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
bgc_ab_240 = iff(ma20 > ma120, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_aB_240 = iff(ma20 > ma20_D, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_bB_240 = color.new(color_1D, transp_fill)
fill(ma20_plot_a_240, ma120_plot_b_240, enable_a_fill_b ? bgc_ab_240 : na, editable = false)
fill(ma20_plot_a_240, ma20_D_plot_B_240, enable_a_fill_B ? bgc_aB_240 : na, editable = false)
fill(ma120_plot_b_240, ma20_D_plot_B_240, bgc_bB_240, editable = false)
// 1W
ma840_plot_c_240 = plot(enable_cC and timeframe.period == "240" ? ma840 : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)
ma20_W_plot_C_240 = plot(enable_cC and timeframe.period == "240" ? ma20_W : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)
bgc_cC_240 = color.new(color_1W, transp_fill)
fill(ma840_plot_c_240, ma20_W_plot_C_240, bgc_cC_240, editable = false)

// -------------------------------------------------- 1D
ma20_plot_a_D = plot(enable_a and timeframe.period == "D" ? ma20 : na,  title = "1D", color = color_1D, linewidth = thickness, transp = transp_ma, editable = false)
ma140_plot_b_D = plot(enable_bB and timeframe.period == "D" ? ma140 : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)
ma20_D_plot_B_D = plot(enable_bB and timeframe.period == "D" ? ma20_W : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)
bgc_ab_D = iff(ma20 > ma140, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_aB_D = iff(ma20 > ma20_W, color.new(color.green, transp_fill_20), color.new(color.red, transp_fill))
bgc_bB_D = color.new(color_1W, transp_fill)
fill(ma20_plot_a_D, ma140_plot_b_D, enable_a_fill_b ? bgc_ab_D : na, editable = false)
fill(ma20_plot_a_D, ma20_D_plot_B_D, enable_a_fill_B ? bgc_aB_D : na, editable = false)
fill(ma140_plot_b_D, ma20_D_plot_B_D, bgc_bB_D, editable = false)

// -------------------------------------------------- 1W
ma20_plot_a_W = plot(enable_a and timeframe.period == "W" ? ma20 : na,  title = "1W", color = color_1W, linewidth = thickness, transp = transp_ma, editable = false)


// -------------------------------------------------- 1M
ma20_plot_a_M = plot(enable_a and timeframe.period == "M" ? ma20 : na,  title = "1M", color = color_1M, linewidth = thickness, transp = transp_ma, editable = false)

 // -------------------------------------------------- 20/50/200 - Common values
bgc_common = iff(ma20 > ma50, color.new(color.green, 80), color.new(color.red, 80))
ma20_plot = plot(enable_common and not enable_a ? ma20 : na,  title = "[20]", color = color_20 , linewidth = thickness, transp = transp_ma, editable = false)
ma50_plot = plot(enable_common ? ma50 : na,  title = "[50]", color = color_50, linewidth = thickness, transp = transp_ma, editable = false)
plot(enable_common ? ma200 : na,  title = "[200]", color = color_200, linewidth = thickness, transp = transp_ma, editable = false)
fill(ma20_plot, ma50_plot, enable_a_fill_50 ? bgc_common : na, editable = false)

