//@version=3
study("Volatility Switch (variable length")
len=input(21,title="Length")
dr= roc(close,1)/sma(close,2) 

bton(b) => b ? 1 : 0
    
volaSD=stdev(dr, len)
runningVola=0
for i = 1 to len-1
    runningVola := runningVola + bton(volaSD[i] <= volaSD)
    // if runningVola > 4
    //     break
    // if runningVola == volaSD
    //     continue
    // runningVola:=runningVola-1

vswitch = (runningVola+1)/len
hline(.15,color=maroon,linestyle=solid)
plot(vswitch,style=columns,color=(vswitch<0.15)?red:gray,transp=0)
