// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © carloswm85

//@version=4
// Built for 1m timeframe trading
//File title: 4SMA20 1m 20/300/1200/4800 @carloswm85

study(title="4SMA20 1m @carloswm85", shorttitle="4SMA20 1m @carloswm85", overlay=true)

a = input(true, title="Enable SMA8")
b = input(true, title="Enable SMA20")
c = input(true, title="Enable SMA50")
d = input(true, title="Enable SMA200")

len1 = input(20, minval=1, title="Input 1")
len2 = input(300, minval=1, title="Input 2")
len3 = input(1200, minval=1, title="Input 3")
len4 = input(4800, minval=1, title="Input 4")

thickness = input(3, minval=1, title="Thickness")
opacity = input(40, minval=1, title="Opacity")
price = close

out1 = sma(price, len1)
out2 = sma(price, len2)
out3 = sma(price, len3)
out4 = sma(price, len4)

plot(a and out1 ? out1: na, title="SMA1", color=#FF00FF, linewidth=thickness, transp=opacity) // fuchsia
plot(b and out2 ? out2: na, title="SMA2", color=#00FFFF, linewidth=thickness, transp=opacity) // aqua
plot(c and out3 ? out3: na, title="SMA3", color=#FFFF00, linewidth=thickness, transp=opacity) // yellow
plot(d and out4 ? out4: na, title="SMA4", color=#ffffff, linewidth=thickness, transp=opacity) // white